### ISSUE TITLE
Mistä tunnukset tänne palveluun

### ISSUE THREAD

**Issue by developerfromjokela** [partio-scout/kuksa-event-api-client#6]
?

**Comment by emilvirkki** [comment]
Partiotoimistolta, varmaan palvelu@partio.fi kannattaa kokeilla. **Tosin:** huomaathan, että tämä rajapinta ja kirjasto on vain suurtapahtumia kuten suurleirejä varten eli esim. lippukuntien tapahtumia ei sieltä saa ulos lainkaan, vaikka tunnukset olisikin. Eli rajapinta on tarkoitettu esim. suurleirin osallistujatietojen hakuun esimerkiksi leirirekisteriin.

**Comment by emilvirkki** [comment]
Jos haluat lippukuntien tapahtumia ulos kuksasta, kannattaa tsekata tämä kirjasto: https://github.com/emilvirkki/kuksa-event-scraper. Siihen ei myöskään tarvitse tunnuksia :)
